//CATEGORY DETAILS
export const GET_CATEGORY_DETAILS_BY_ID_REQUEST="GET_CATEGORY_DETAILS_BY_ID_REQUEST";
export const GET_CATEGORY_DETAILS_BY_ID_SUCCESS="GET_CATEGORY_DETAILS_BY_ID_SUCCESS";
export const GET_CATEGORY_DETAILS_BY_ID_FAILURE="GET_CATEGORY_DETAILS_BY_ID_FAILURE";

// LIST OF BOOK BY CATEGORY ID

export const GET_BOOK_LIST_BY_ID_REQUEST="GET_BOOK_LIST_BY_ID_REQUEST";
export const GET_BOOK_LIST_BY_ID_SUCCESS="GET_BOOK_LIST_BY_ID_SUCCESS";
export const GET_BOOK_LIST_BY_ID_FAILURE="GET_BOOK_LIST_BY_ID_FAILURE";

// BOOK DETAILS

export const GET_BOOK_DETAILS_ID_REQUEST="GET_BOOK_DETAILS_ID_REQUEST";
export const GET_BOOK_DETAILS_ID_SUCCESS="GET_BOOK_DETAILS_ID_SUCCESS";
export const GET_BOOK_DETAILS_ID_FAILURE="GET_BOOK_DETAILS_ID_FAILURE";